# Generated by Django 5.2 on 2026-01-06 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_alter_codefile_options_passwordotp_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['owner', '-updated_at'], name='core_codefi_owner_i_9656e3_idx'),
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['owner', 'filename'], name='core_codefi_owner_i_090b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordotp',
            index=models.Index(fields=['user', '-created_at'], name='core_passwo_user_id_6634da_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-updated_at'], name='core_userpr_updated_102bc4_idx'),
        ),
    ]
