# Generated by Django 5.2 on 2026-02-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workspace_board_task'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='board',
            new_name='core_board_workspa_859324_idx',
            old_name='core_board_workspa_0d238a_idx',
        ),
        migrations.RenameIndex(
            model_name='column',
            new_name='core_column_board_i_2a23df_idx',
            old_name='core_column_board_id_7f8f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_board_i_11e9bb_idx',
            old_name='core_task_board_i_8de4cd_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_board_i_c44d44_idx',
            old_name='core_task_board_i_7d2bb0_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_due_dat_d0a0d3_idx',
            old_name='core_task_due_da_6f97ae_idx',
        ),
        migrations.RenameIndex(
            model_name='taskcomment',
            new_name='core_taskco_task_id_b10483_idx',
            old_name='core_taskco_task_id_dad1a7_idx',
        ),
        migrations.RenameIndex(
            model_name='team',
            new_name='core_team_code_564e78_idx',
            old_name='core_team_code_2d2c42_idx',
        ),
        migrations.RenameIndex(
            model_name='teammembership',
            new_name='core_teamme_team_id_31ddcd_idx',
            old_name='core_teamm_team_id_7d3e45_idx',
        ),
        migrations.RenameIndex(
            model_name='teammembership',
            new_name='core_teamme_user_id_459085_idx',
            old_name='core_teamm_user_id_82d2e7_idx',
        ),
        migrations.RenameIndex(
            model_name='workspace',
            new_name='core_worksp_team_id_b9ee1f_idx',
            old_name='core_worksp_team_id_5e5f61_idx',
        ),
    ]
