# Generated by Django 5.2 on 2026-03-01 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_emailverificationotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('target_type', models.CharField(blank=True, default='', max_length=30)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, default='', max_length=220)),
                ('detail', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('is_done', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='emailverificationotp',
            new_name='core_emailv_email_6c8623_idx',
            old_name='core_emailve_email_0cf518_idx',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.team'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.task'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.task'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['team', '-created_at'], name='core_activi_team_id_999c20_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task', 'position'], name='core_subtas_task_id_b5db65_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task', '-created_at'], name='core_taskat_task_id_a92380_idx'),
        ),
    ]
