# Generated by Django 5.2 on 2026-03-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_activitylog_subtask_taskattachment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='team',
            name='core_team_code_564e78_idx',
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
