# Generated by Django 5.2 on 2026-04-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_timeentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
