# Generated by Django 5.2 on 2026-04-06 08:36

import uuid
from django.db import migrations, models


def populate_tokens(apps, schema_editor):
    TeamInvitation = apps.get_model('core', 'TeamInvitation')
    for inv in TeamInvitation.objects.filter(token=''):
        inv.token = uuid.uuid4().hex
        inv.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_teaminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='token',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.RunPython(populate_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='teaminvitation',
            name='token',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
    ]
