# Generated by Django 5.2 on 2026-04-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
