# Generated by Django 5.0.6 on 2026-04-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_task_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='blocking', to='core.task'),
        ),
    ]
